# Generated by Django 3.2 on 2023-06-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_remove_comment_flat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='published',
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.CharField(default=1, max_length=128, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='phone',
            field=models.CharField(default=1, max_length=32, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=32, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_of_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата отправления'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Содержимое письма'),
        ),
    ]
